// <auto-generated />
using System;
using AnsibeProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnsibeProject.Migrations
{
    [DbContext(typeof(UniversityContext))]
    partial class UniversityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnsibeProject.Models.Ansibe", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Ansibes", (string)null);
                });

            modelBuilder.Entity("AnsibeProject.Models.Contract", b =>
                {
                    b.Property<string>("ContractType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaxHours")
                        .HasColumnType("int");

                    b.Property<int?>("MinHours")
                        .HasColumnType("int");

                    b.HasKey("ContractType");

                    b.ToTable("Contracts", (string)null);
                });

            modelBuilder.Entity("AnsibeProject.Models.Course", b =>
                {
                    b.Property<string>("CourseCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("CourseState")
                        .HasColumnType("int");

                    b.Property<int>("Major")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfCredits")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfHours")
                        .HasColumnType("int");

                    b.Property<int>("Obligatory")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<int>("TD")
                        .HasColumnType("int");

                    b.Property<int>("TP")
                        .HasColumnType("int");

                    b.Property<int>("TotalNumberOfHours")
                        .HasColumnType("int");

                    b.HasKey("CourseCode");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("AnsibeProject.Models.Professor", b =>
                {
                    b.Property<int>("FileNumber")
                        .HasColumnType("int");

                    b.Property<int>("ActiveState")
                        .HasColumnType("int");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullNameInArabic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("FileNumber");

                    b.HasIndex("ContractType");

                    b.ToTable("Professors", (string)null);
                });

            modelBuilder.Entity("AnsibeProject.Models.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<string>("AnsibeId")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CourseHours")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<int?>("ProfessorFileNumber")
                        .HasColumnType("int");

                    b.Property<int?>("TD")
                        .HasColumnType("int");

                    b.Property<int?>("TP")
                        .HasColumnType("int");

                    b.HasKey("SectionId");

                    b.HasIndex("AnsibeId");

                    b.HasIndex("CourseCode");

                    b.HasIndex("ProfessorFileNumber");

                    b.ToTable("Sections", (string)null);
                });

            modelBuilder.Entity("AnsibeProject.Models.Professor", b =>
                {
                    b.HasOne("AnsibeProject.Models.Contract", "Contract")
                        .WithMany("Professors")
                        .HasForeignKey("ContractType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("AnsibeProject.Models.Section", b =>
                {
                    b.HasOne("AnsibeProject.Models.Ansibe", null)
                        .WithMany("Sections")
                        .HasForeignKey("AnsibeId");

                    b.HasOne("AnsibeProject.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnsibeProject.Models.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorFileNumber");

                    b.Navigation("Course");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("AnsibeProject.Models.Ansibe", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("AnsibeProject.Models.Contract", b =>
                {
                    b.Navigation("Professors");
                });
#pragma warning restore 612, 618
        }
    }
}
